"""Convenience imports for prompt templates."""

from .article import PROMPT_ARTICLE_WRITER
from .book import (PROMPT_BOOK_PLANNER, PROMPT_CHAPTER_WRITER, PROMPT_PLANNER,
                   PROMPT_REVIEWER)
from .common import (PROMPT_GROUNDED_QA_GENERATOR, PROMPT_QA_GENERATOR,
                     PROMPT_UNGROUNDED_QA_GENERATOR, SYSTEM_PROMPT)
from .dialogue import PROMPT_DIALOGUE_PLANNER, PROMPT_EXCHANGE_WRITER
from .domain import PROMPT_TOPIC_PLANNER
from .poem import PROMPT_POEM_PLANNER, PROMPT_STANZA_WRITER

__all__ = [
    "PROMPT_ARTICLE_WRITER",
    "PROMPT_BOOK_PLANNER",
    "PROMPT_CHAPTER_WRITER",
    "PROMPT_DIALOGUE_PLANNER",
    "PROMPT_EXCHANGE_WRITER",
    "PROMPT_GROUNDED_QA_GENERATOR",
    "PROMPT_PLANNER",
    "PROMPT_POEM_PLANNER",
    "PROMPT_QA_GENERATOR",
    "PROMPT_REVIEWER",
    "PROMPT_STANZA_WRITER",
    "PROMPT_TOPIC_PLANNER",
    "PROMPT_UNGROUNDED_QA_GENERATOR",
    "SYSTEM_PROMPT",
]
